basic:
    name: 'https://reflect-design-co-b9e951.webflow.io/'
    environments:
        production: 'https://reflect-design-co-b9e951.webflow.io/'
        staging: ''
        development: ''
    breakpoints:
        - 375
        - 768
        - 1440
    pages:
        - /
        - catalogue
        - photo
        - about
        - process
        - contact
        - encore
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
